"use client";

import { escapeHtml } from "./attendance-utils";

export interface AttendanceExportColumn<T> {
  label: string;
  value: (row: T, index: number) => string | number;
}

export function printAttendanceReport<T>(input: { title: string; meta: string; columns: AttendanceExportColumn<T>[]; rows: T[]; summary?: string }) {
  const printWindow = window.open("", "_blank");
  if (!printWindow) throw new Error("Please allow popups to print");
  const html = `<!DOCTYPE html><html><head><title>${escapeHtml(input.title)}</title><style>*{box-sizing:border-box}body{font-family:Inter,Arial,sans-serif;color:#1f2937;padding:24px}h1{font-size:20px;margin:0 0 4px}.meta{font-size:12px;color:#6b7280;margin-bottom:18px}.summary{border:1px solid #e5e7eb;background:#f9fafb;border-radius:8px;padding:10px 12px;margin-bottom:16px;font-size:12px}table{width:100%;border-collapse:collapse;font-size:11px}th{background:#f3f4f6;text-align:left;padding:8px;border-bottom:2px solid #d1d5db}td{padding:8px;border-bottom:1px solid #e5e7eb}tr:nth-child(even){background:#fafafa}.footer{text-align:center;color:#9ca3af;font-size:10px;margin-top:16px}@media print{body{padding:10px}}</style></head><body><h1>${escapeHtml(input.title)}</h1><div class="meta">${escapeHtml(input.meta)}</div>${input.summary ? `<div class="summary">${escapeHtml(input.summary)}</div>` : ""}<table><thead><tr>${input.columns.map((column) => `<th>${escapeHtml(column.label)}</th>`).join("")}</tr></thead><tbody>${input.rows.map((row, index) => `<tr>${input.columns.map((column) => `<td>${escapeHtml(column.value(row, index))}</td>`).join("")}</tr>`).join("")}</tbody></table><div class="footer">Generated by School ERP on ${escapeHtml(new Date().toLocaleString())}</div></body></html>`;
  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => printWindow.print(), 500);
}

export function exportAttendanceExcel<T>(input: { filename: string; sheetName: string; columns: AttendanceExportColumn<T>[]; rows: T[]; summaryRow?: Array<string | number> }) {
  const XLSX = require("xlsx-js-style");
  const data: Array<Array<string | number>> = [input.columns.map((column) => column.label), ...input.rows.map((row, index) => input.columns.map((column) => column.value(row, index)))];
  if (input.summaryRow) data.push([], input.summaryRow);
  const sheet = XLSX.utils.aoa_to_sheet(data);
  const headerLength = input.columns.length;
  for (let column = 0; column < headerLength; column += 1) {
    const cell = sheet[XLSX.utils.encode_cell({ r: 0, c: column })];
    if (cell) cell.s = { fill: { fgColor: { rgb: "4F46E5" } }, font: { bold: true, color: { rgb: "FFFFFF" } }, alignment: { horizontal: "center" }, border: { bottom: { style: "thin", color: { rgb: "4F46E5" } } } };
  }
  for (let row = 1; row < data.length; row += 1) for (let column = 0; column < headerLength; column += 1) {
    const cell = sheet[XLSX.utils.encode_cell({ r: row, c: column })];
    if (cell) cell.s = { fill: { fgColor: { rgb: row % 2 === 0 ? "F3F4F6" : "FFFFFF" } }, border: { bottom: { style: "thin", color: { rgb: "E5E7EB" } } }, alignment: { vertical: "center" } };
  }
  sheet["!cols"] = input.columns.map((column) => ({ wch: Math.max(14, column.label.length + 5) }));
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, sheet, input.sheetName.slice(0, 31));
  XLSX.writeFile(workbook, input.filename);
}
