import { NextResponse } from "next/server";
import { z } from "zod";
import { getSchoolSession } from "@/lib/auth/jwt";
import { AppError, error, success } from "@/lib/api-response";
import { createClassPeriods, deleteClassPeriod, duplicateClassPeriods, getClassPeriods, updateClassPeriod } from "@/services/timetable.service";

const Time = z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/, "Use a valid time");
const CreateSchema = z.object({ class_id: z.string().uuid(), weekday_ids: z.array(z.string().uuid()).min(1), label: z.string().trim().min(1).max(40), position: z.number().int().min(1), start_time: Time, end_time: Time });
const UpdateSchema = z.object({ id: z.string().uuid(), label: z.string().trim().min(1).max(40).optional(), position: z.number().int().min(1).optional(), start_time: Time.optional(), end_time: Time.optional() });
const DeleteSchema = z.object({ id: z.string().uuid() });
const DuplicateSchema = z.object({ action: z.literal("duplicate"), source_class_id: z.string().uuid(), target_class_ids: z.array(z.string().uuid()).min(1) });
async function allowed(id: string) { const s = await getSchoolSession(); return s?.role === "admin" && s.schoolId === id; }
function failure(value: unknown) { const e = value instanceof Error ? value : new Error("Period operation failed"); return NextResponse.json(error(e.message), { status: e instanceof AppError ? e.statusCode : 500 }); }

export async function GET(req: Request, { params }: { params: Promise<{ schoolId: string }> }) { const { schoolId } = await params; try { if (!(await allowed(schoolId))) return NextResponse.json(error("Unauthorized"), { status: 401 }); const classId = new URL(req.url).searchParams.get("classId"); if (!classId) return NextResponse.json(error("Class is required"), { status: 400 }); return NextResponse.json(success(await getClassPeriods(schoolId, classId))); } catch (e) { return failure(e); } }
export async function POST(req: Request, { params }: { params: Promise<{ schoolId: string }> }) { const { schoolId } = await params; try { if (!(await allowed(schoolId))) return NextResponse.json(error("Unauthorized"), { status: 401 }); const json = await req.json(); if (json.action === "duplicate") { const p = DuplicateSchema.safeParse(json); if (!p.success) return NextResponse.json(error("Choose source and target classes"), { status: 400 }); return NextResponse.json(success(await duplicateClassPeriods(schoolId, p.data.source_class_id, p.data.target_class_ids))); } const p = CreateSchema.safeParse(json); if (!p.success) return NextResponse.json(error(p.error.issues[0]?.message ?? "Invalid period"), { status: 400 }); if (p.data.end_time <= p.data.start_time) return NextResponse.json(error("End time must be after start time"), { status: 400 }); return NextResponse.json(success(await createClassPeriods(schoolId, p.data))); } catch (e) { return failure(e); } }
export async function PATCH(req: Request, { params }: { params: Promise<{ schoolId: string }> }) { const { schoolId } = await params; try { if (!(await allowed(schoolId))) return NextResponse.json(error("Unauthorized"), { status: 401 }); const p = UpdateSchema.safeParse(await req.json()); if (!p.success) return NextResponse.json(error("Invalid period"), { status: 400 }); const { id, ...input } = p.data; return NextResponse.json(success(await updateClassPeriod(schoolId, id, input))); } catch (e) { return failure(e); } }
export async function DELETE(req: Request, { params }: { params: Promise<{ schoolId: string }> }) { const { schoolId } = await params; try { if (!(await allowed(schoolId))) return NextResponse.json(error("Unauthorized"), { status: 401 }); const p = DeleteSchema.safeParse(await req.json()); if (!p.success) return NextResponse.json(error("Invalid period"), { status: 400 }); await deleteClassPeriod(schoolId, p.data.id); return NextResponse.json(success({ deleted: true })); } catch (e) { return failure(e); } }
